server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://47.116.216.209:3306/xyc_mall
    username: root
    password: xycmall20240204
  redis:
    port: 6379
    password: xyc20240303
    host: 47.116.216.209
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 100